const load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
let groups=load('fgp_groups',[]),posts=load('fgp_posts',[]),schedules=load('fgp_schedules',[]),history=load('fgp_history',[]),imagePath=localStorage.getItem('fgp_image')||'',running=false,timer=null,batch=0,editingPost=null,calendarCursor=new Date(),selectedCalendarDate=new Date();
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem('fgp_groups',JSON.stringify(groups));localStorage.setItem('fgp_posts',JSON.stringify(posts));localStorage.setItem('fgp_schedules',JSON.stringify(schedules));localStorage.setItem('fgp_history',JSON.stringify(history));if(imagePath)localStorage.setItem('fgp_image',imagePath);else localStorage.removeItem('fgp_image')}
function toast(x){$('toast').textContent=x;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function state(g){return g.status||'ready'} function stateLabel(s){return {ready:'Sẵn sàng',pending:'Đang chờ',error:'Lỗi',done:'Đã xử lý'}[s]||s}
function updateStats(){let done=groups.filter(g=>state(g)==='done').length;$('statGroups').textContent=groups.length;$('statPosts').textContent=posts.length;$('statScheduled').textContent=schedules.filter(s=>s.status==='scheduled').length;$('statDone').textContent=done}
function fillPostSelects(){let opts=posts.length?posts.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join(''):'<option value="">Chưa có bài đăng</option>';['quickPost','schedulePost'].forEach(id=>{let el=$(id),old=el.value;el.innerHTML=opts;if([...el.options].some(o=>o.value===old))el.value=old});}
function renderPosts(){ $('postCount').textContent=posts.length; $('posts').innerHTML=posts.length?posts.map(p=>`<div class="post-card ${p.id===editingPost?'selected':''}"><div><b>${esc(p.title)}</b><small>${esc(p.content.slice(0,120).replace(/\n/g,' '))}</small><span>${p.content.length.toLocaleString('vi-VN')} ký tự • ${new Date(p.updated).toLocaleString('vi-VN')}</span></div><div class="post-actions"><button data-edit="${p.id}" class="secondary">Sửa</button><button data-sched="${p.id}" class="secondary">Lên lịch</button><button data-postdel="${p.id}" class="text-btn">Xóa</button></div></div>`).join(''):'<div class="empty">Chưa có bài đăng. Tạo bài đầu tiên ở bên trên.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPost(b.dataset.edit));document.querySelectorAll('[data-sched]').forEach(b=>b.onclick=()=>{fillPostSelects();$('schedulePost').value=b.dataset.sched;activate('schedule')});document.querySelectorAll('[data-postdel]').forEach(b=>b.onclick=()=>{posts=posts.filter(p=>p.id!==b.dataset.postdel);if(editingPost===b.dataset.postdel)resetEditor();save();renderAll();toast('Đã xóa bài')})}
function editPost(id){let p=posts.find(x=>x.id===id);if(!p)return;editingPost=id;$('postTitle').value=p.title;$('content').value=p.content;imagePath=p.image||'';showImage();$('content').dispatchEvent(new Event('input'));activate('posts')}
function resetEditor(){editingPost=null;$('postTitle').value='';$('content').value='';imagePath='';showImage();$('content').dispatchEvent(new Event('input'))}
function renderGroups(){let q=$('groupSearch').value.trim().toLowerCase(),f=$('statusFilter').value;let shown=groups.map((g,i)=>({g,i})).filter(x=>(!q||x.g.name.toLowerCase().includes(q)||x.g.url.toLowerCase().includes(q))&&(f==='all'||state(x.g)===f));$('groupCount').textContent=`${groups.length} nhóm`;$('groups').innerHTML=shown.length?shown.map(({g,i})=>`<div class="group"><input class="pick" type="checkbox" data-i="${i}" ${g.selected!==false?'checked':''}><div class="group-main"><b>${esc(g.name)}</b><small>${esc(g.url)}</small></div><select class="status-select" data-status="${i}"><option value="ready" ${state(g)==='ready'?'selected':''}>Sẵn sàng</option><option value="pending" ${state(g)==='pending'?'selected':''}>Đang chờ</option><option value="error" ${state(g)==='error'?'selected':''}>Lỗi</option><option value="done" ${state(g)==='done'?'selected':''}>Đã xử lý</option></select><button data-del="${i}">Xóa</button></div>`).join(''):'<div class="empty">Không có nhóm phù hợp.</div>';document.querySelectorAll('.pick').forEach(c=>c.onchange=()=>{groups[+c.dataset.i].selected=c.checked;save();renderAll()});document.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>{groups[+s.dataset.status].status=s.value;save();renderAll();toast('Đã cập nhật trạng thái')});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{groups.splice(+b.dataset.del,1);save();renderAll()});renderScheduleGroups();renderStatusSummary()}
function selected(){return groups.filter(g=>g.selected!==false)}
function renderStatusSummary(){let counts={ready:0,pending:0,error:0,done:0};groups.forEach(g=>counts[state(g)]++);$('statusSummary').innerHTML=Object.entries(counts).map(([k,v])=>`<div><span class="dot ${k}"></span><b>${v}</b><small>${stateLabel(k)}</small></div>`).join('')}
function renderScheduleGroups(){let s=groups.map((g,i)=>`<label class="mini-group"><input type="checkbox" data-sg="${i}" ${g.selected!==false?'checked':''}><span>${esc(g.name)}</span></label>`).join('');$('scheduleGroups').innerHTML=s||'<span class="muted">Chưa có nhóm</span>'}
function renderProgress(){let list=selected(),done=list.filter(g=>history.some(h=>h.batch===batch&&h.url===g.url&&h.state==='Đã mở')).length;$('progressText').textContent=`${done} / ${list.length}`;$('progressBar').style.width=(list.length?done/list.length*100:0)+'%';$('progress').innerHTML=list.length?list.map(g=>{let h=history.find(x=>x.batch===batch&&x.url===g.url);let st=h?.state||'Chờ';return `<div class="row"><div class="row-main"><b>${esc(g.name)}</b><small>${esc(g.url)}</small></div><span class="status ${st==='Đã mở'?'ok':st==='Đang xử lý'?'processing':''}">${st}</span></div>`}).join(''):'<div class="empty">Chưa chọn group.</div>'}
function addHistory(g,state,b=batch){history.unshift({name:g.name,url:g.url,state,time:new Date().toLocaleString('vi-VN'),batch:b});history=history.slice(0,200);save();renderHistory();renderProgress();updateStats()}
function renderHistory(){ $('history').innerHTML=history.length?history.map(h=>`<div class="row"><div class="row-main"><b>${esc(h.name)}</b><small>${esc(h.time)} • phiên ${h.batch}</small></div><span class="status ${h.state==='Đã mở'?'ok':''}">${esc(h.state)}</span></div>`).join(''):'<div class="empty">Chưa có lịch sử.</div>' }
function dateKey(d){const x=new Date(d);return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')}
function localDateFromKey(k){const a=k.split('-').map(Number);return new Date(a[0],a[1]-1,a[2])}
function renderDayDetails(){const key=dateKey(selectedCalendarDate);const items=schedules.filter(s=>dateKey(s.when)===key);$('dayDetailTitle').textContent=localDateFromKey(key).toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});$('dayScheduleCount').textContent=items.length;if(!items.length){$('dayDetails').innerHTML='<div class="empty-day">Không có bài nào được lên lịch trong ngày này.</div>';return} $('dayDetails').innerHTML=items.sort((a,b)=>new Date(a.when)-new Date(b.when)).map(s=>{const p=posts.find(x=>x.id===s.postId);const names=s.groups.map(u=>groups.find(g=>g.url===u)?.name||u);return `<div class="day-detail"><div class="detail-top"><div><b>${esc(p?.title||'Bài đã xóa')}</b><div class="detail-meta">${new Date(s.when).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})} • ${s.groups.length} nhóm • cách ${s.delay} phút</div></div><span class="status ${s.status==='scheduled'?'processing':'ok'}">${s.status==='scheduled'?'Đã lên lịch':s.status==='cancelled'?'Đã hủy':'Đã chạy'}</span></div><div class="detail-groups">${names.slice(0,12).map(n=>`<span class="group-chip">${esc(n)}</span>`).join('')}${names.length>12?`<span class="group-chip">+${names.length-12} nhóm</span>`:''}</div></div>`}).join('')}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();$('calendarTitle').textContent=first.toLocaleDateString('vi-VN',{month:'long',year:'numeric'});let html=['T2','T3','T4','T5','T6','T7','CN'].map(x=>`<div class="cal-weekday">${x}</div>`).join('');for(let i=0;i<42;i++){const n=i-start+1,cellDate=n<1?new Date(y,m-1,prev+n):n>days?new Date(y,m+1,n-days):new Date(y,m,n);const key=dateKey(cellDate),events=schedules.filter(s=>dateKey(s.when)===key);html+=`<div class="cal-cell ${cellDate.getMonth()!==m?'other ':''}${key===dateKey(new Date())?'today ':''}${key===dateKey(selectedCalendarDate)?'selected ':''}" data-date="${key}"><div class="cal-date">${cellDate.getDate()}</div><div class="cal-events">${events.slice(0,4).map(s=>{const p=posts.find(x=>x.id===s.postId);return `<div class="cal-event ${s.status}" draggable="true" data-sid="${s.id}" title="Kéo để đổi ngày">${new Date(s.when).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})} · ${esc(p?.title||'Bài đã xóa')}</div>`}).join('')}${events.length>4?`<div class="muted">+${events.length-4} lịch</div>`:''}</div></div>`}$('calendar').innerHTML=html;document.querySelectorAll('.cal-cell').forEach(c=>{c.onclick=e=>{if(e.target.closest('.cal-event'))return;selectedCalendarDate=localDateFromKey(c.dataset.date);renderCalendar();renderDayDetails()};c.ondragover=e=>{e.preventDefault();c.classList.add('drag-over')};c.ondragleave=()=>c.classList.remove('drag-over');c.ondrop=e=>{e.preventDefault();c.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain'),s=schedules.find(x=>x.id===id);if(!s)return;const old=new Date(s.when),d=localDateFromKey(c.dataset.date);d.setHours(old.getHours(),old.getMinutes(),0,0);if(d.getTime()<=Date.now())return toast('Không thể kéo lịch về thời gian đã qua');s.when=d.toISOString();save();selectedCalendarDate=d;renderAll();scheduleRuntime(s);toast('Đã đổi ngày lịch đăng')}});document.querySelectorAll('.cal-event').forEach(el=>el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.sid)})}
function renderSchedules(){let now=Date.now();schedules=schedules.filter(s=>s.status!=='expired'||new Date(s.when).getTime()>now-86400000);$('scheduleCount').textContent=schedules.filter(s=>s.status==='scheduled').length;$('schedules').innerHTML=schedules.length?schedules.sort((a,b)=>new Date(a.when)-new Date(b.when)).map(s=>{let p=posts.find(x=>x.id===s.postId);return `<div class="row"><div class="row-main"><b>${esc(p?.title||'Bài đã xóa')}</b><small>${new Date(s.when).toLocaleString('vi-VN')} • ${s.groups.length} nhóm • cách ${s.delay} phút</small></div><span class="status ${s.status==='scheduled'?'processing':'ok'}">${s.status==='scheduled'?'Đã lên lịch':'Đã chạy'}</span>${s.status==='scheduled'?`<button class="text-btn" data-cancel="${s.id}">Hủy</button>`:''}</div>`}).join(''):'<div class="empty">Chưa có lịch đăng.</div>';document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancelSchedule(b.dataset.cancel));renderUpcoming()}
function renderUpcoming(){let a=schedules.filter(s=>s.status==='scheduled').sort((x,y)=>new Date(x.when)-new Date(y.when)).slice(0,5);$('upcoming').innerHTML=a.length?a.map(s=>{let p=posts.find(x=>x.id===s.postId);return `<div class="row"><div class="row-main"><b>${esc(p?.title||'Bài đã xóa')}</b><small>${new Date(s.when).toLocaleString('vi-VN')} • ${s.groups.length} nhóm</small></div><span class="status processing">Đã lên lịch</span></div>`}).join(''):'<div class="empty">Chưa có lịch sắp tới.</div>'}
function showImage(){if(imagePath){$('imagePath').textContent=imagePath;$('preview').src='file:///'+imagePath.replaceAll('\\','/');$('preview').hidden=false}else{$('imagePath').textContent='Chưa chọn ảnh';$('preview').hidden=true}}
async function runQueue(list,i,b){if(!running||i>=list.length){running=false;toast(i>=list.length?'Đã hoàn tất hàng đợi':'Đã dừng hàng đợi');renderProgress();return}let g=list[i];g.status='pending';addHistory(g,'Đang xử lý',b);try{await navigator.clipboard.writeText($('quickPost').value?posts.find(p=>p.id===$('quickPost').value)?.content:'')}catch(e){}window.open(g.url,'_blank');g.status='done';addHistory(g,'Đã mở',b);if(i<list.length-1)timer=setTimeout(()=>runQueue(list,i+1,b),+$('delay').value*60000);else{save();renderAll()}}
function activate(tab){document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+tab));let meta={overview:['Tổng quan','Quản lý bài đăng, nhóm, lịch đăng và trạng thái trong một nơi.'],posts:['Bài đăng','Kho nội dung và mẫu bài đăng.'],groups:['Hội nhóm','Lọc, chọn và cập nhật trạng thái từng nhóm.'],schedule:['Lịch đăng','Lên lịch các phiên đăng theo ngày và giờ.'],history:['Lịch sử','Theo dõi trạng thái từng nhóm trong từng phiên.']}[tab];$('pageTitle').textContent=meta[0];$('pageSub').textContent=meta[1]}
function renderAll(){fillPostSelects();renderPosts();renderGroups();renderSchedules();renderHistory();renderProgress();updateStats();renderCalendar();renderDayDetails()}
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>activate(n.dataset.tab));document.querySelectorAll('[data-tab-jump]').forEach(b=>b.onclick=()=>activate(b.dataset.tabJump));
$('newPost').onclick=()=>{resetEditor();toast('Tạo bài đăng mới')};$('savePost').onclick=()=>{let title=$('postTitle').value.trim()||'Bài đăng '+(posts.length+1),content=$('content').value.trim();if(!content)return toast('Nhập nội dung trước');if(editingPost){let p=posts.find(x=>x.id===editingPost);Object.assign(p,{title,content,image:imagePath,updated:Date.now()})}else{let p={id:'p_'+Date.now(),title,content,image:imagePath,updated:Date.now()};posts.unshift(p);editingPost=p.id}save();renderAll();toast('Đã lưu bài đăng')};$('content').oninput=()=>$('charCount').textContent=$('content').value.length.toLocaleString('vi-VN')+' ký tự';$('clearContent').onclick=()=>{$('content').value='';$('content').dispatchEvent(new Event('input'))};$('pasteBtn').onclick=()=>{$('content').value='☕ CỐT CÀ PHÊ ĐẬM ĐẶC – PHA NHANH TẠI NHÀ\n\nKhông cần pha phin, chỉ cần rót ra là dùng.\n300ml/chai – tiện lợi, thơm đậm vị.\n\n📩 Inbox để đặt hàng.';$('content').dispatchEvent(new Event('input'));toast('Đã thêm mẫu')};$('chooseImage').onclick=async()=>{let p=await window.desktop.pickImage();if(p){imagePath=p;showImage()}};$('removeImage').onclick=()=>{imagePath='';showImage()};
$('addGroup').onclick=()=>{let n=$('groupName').value.trim(),u=$('groupUrl').value.trim();if(!n||!/^https?:\/\//i.test(u))return toast('Nhập tên và link group hợp lệ');if(groups.some(g=>g.url===u))return toast('Group đã tồn tại');groups.push({name:n,url:u,selected:true,status:'ready'});$('groupName').value='';$('groupUrl').value='';save();renderAll();toast('Đã thêm group')};$('groupSearch').oninput=renderGroups;$('statusFilter').onchange=renderGroups;$('selectAll').onclick=()=>{let next=groups.filter(g=>g.selected!==false).length!==groups.length;groups.forEach(g=>g.selected=next);save();renderAll();toast(next?'Đã chọn tất cả':'Đã bỏ chọn tất cả')};
$('start').onclick=()=>{if(running)return;if(!posts.length)return toast('Tạo ít nhất một bài đăng');let p=posts.find(x=>x.id===$('quickPost').value);if(!p||!p.content.trim())return toast('Bài đăng chưa có nội dung');let list=selected();if(!list.length)return toast('Chọn ít nhất một group');running=true;batch=Date.now();renderProgress();runQueue(list,0,batch)};$('stop').onclick=()=>{running=false;clearTimeout(timer);toast('Đã dừng hàng đợi');renderProgress()};
$('scheduleBtn').onclick=()=>{let postId=$('schedulePost').value,ds=$('scheduleDate').value,ts=$('scheduleTime').value;let picked=[...document.querySelectorAll('[data-sg]:checked')].map(x=>groups[+x.dataset.sg]).filter(Boolean);if(!postId||!posts.length)return toast('Chưa có bài đăng');if(!ds||!ts)return toast('Chọn ngày và giờ');if(!picked.length)return toast('Chọn ít nhất một group');let when=new Date(ds+'T'+ts);if(when.getTime()<=Date.now())return toast('Thời gian phải ở tương lai');let s={id:'s_'+Date.now(),postId,when:when.toISOString(),delay:+$('scheduleDelay').value,groups:picked.map(g=>g.url),status:'scheduled'};schedules.push(s);save();renderAll();scheduleRuntime(s);toast('Đã tạo lịch đăng')};
function cancelSchedule(id){let s=schedules.find(x=>x.id===id);if(s){s.status='cancelled';save();renderAll();toast('Đã hủy lịch')}}function scheduleRuntime(s){let wait=new Date(s.when).getTime()-Date.now();if(wait<=0){executeSchedule(s);return}setTimeout(()=>executeSchedule(s),wait)}async function executeSchedule(s){if(s.status!=='scheduled')return;let p=posts.find(x=>x.id===s.postId);if(!p)return;s.groups.forEach(url=>{let g=groups.find(x=>x.url===url);if(g){g.status='pending';addHistory(g,'Đang xử lý',s.id)}});try{await navigator.clipboard.writeText(p.content)}catch(e){}s.status='done';s.groups.forEach(url=>{let g=groups.find(x=>x.url===url);if(g){window.open(g.url,'_blank');g.status='done';addHistory(g,'Đã mở',s.id)}});save();renderAll();toast('Đã chạy lịch đăng')}
$('clearHistory').onclick=()=>{history=[];save();renderAll();toast('Đã xóa lịch sử')};$('exportBtn').onclick=()=>{let d={version:'V3.2.1',groups,posts,schedules,history},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download='facebook-poster-v3.2-data.json';a.click()};
$('calPrev').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar()};$('calNext').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar()};$('calToday').onclick=()=>{calendarCursor=new Date();selectedCalendarDate=new Date();renderCalendar();renderDayDetails()};let tomorrow=new Date(Date.now()+86400000);$('scheduleDate').value=tomorrow.toISOString().slice(0,10);renderAll();$('content').dispatchEvent(new Event('input'));schedules.filter(s=>s.status==='scheduled').forEach(scheduleRuntime);


// V3.2.1 Auto Updater
let APP_VERSION='3.2.1';
window.desktop.getAppVersion().then(v=>{if(v){APP_VERSION=v;}}).catch(()=>{});
function allData(){return {groups,posts,schedules,history,imagePath};}
function openUpdateModal(){ $('updateModal').hidden=false; $('currentVersion').textContent='V'+APP_VERSION; $('newVersion').textContent='—'; $('updateProgressBar').style.width='0%'; $('updateProgressText').textContent='Sẵn sàng'; $('updateMessage').textContent='Nhấn kiểm tra để tìm phiên bản mới.'; $('updateAction').dataset.mode='check'; $('updateAction').textContent='Kiểm tra phiên bản'; $('updateAction').disabled=false; }
$('updateBtn').onclick=openUpdateModal;
$('closeUpdate').onclick=()=>{$('updateModal').hidden=true};
$('openBackups').onclick=()=>window.desktop.openBackupFolder();
$('updateAction').onclick=async()=>{
  const mode=$('updateAction').dataset.mode||'check';
  if(mode==='download'){const r=await window.desktop.downloadUpdate(allData());if(!r?.ok)toast('Không thể tải bản cập nhật');return;}
  if(mode==='install'){await window.desktop.installUpdate(allData());return;}
  $('updateAction').disabled=true;$('updateMessage').textContent='Đang kiểm tra phiên bản...';await window.desktop.checkForUpdates();
};
window.desktop.onUpdateStatus(st=>{
  if(st.status==='checking'){$('updateMessage').textContent='Đang kết nối máy chủ cập nhật...';$('updateProgressText').textContent='Đang kiểm tra...';}
  if(st.status==='latest'){$('updateMessage').textContent='Bạn đang dùng phiên bản mới nhất.';$('newVersion').textContent='V'+APP_VERSION;$('updateProgressText').textContent='Đã cập nhật';$('updateAction').dataset.mode='close';$('updateAction').textContent='Đóng';$('updateAction').disabled=false;$('updateAction').onclick=()=>{$('updateModal').hidden=true};}
  if(st.status==='available'){$('newVersion').textContent='V'+st.version;$('updateMessage').textContent='Đã tìm thấy phiên bản mới. Dữ liệu sẽ được sao lưu trước khi tải.';$('updateProgressText').textContent='Có bản mới';$('updateAction').dataset.mode='download';$('updateAction').textContent='Tải bản mới';$('updateAction').disabled=false;}
  if(st.status==='downloading'){$('updateMessage').textContent='Đang tải bản cập nhật...';$('updateProgressText').textContent=`Đang tải ${st.progress||0}%`;$('updateProgressBar').style.width=(st.progress||0)+'%';$('updateAction').disabled=true;}
  if(st.status==='downloaded'){$('updateMessage').textContent='Đã tải xong. Có thể cài đặt và khởi động lại app.';$('updateProgressText').textContent='Tải xong';$('updateProgressBar').style.width='100%';$('updateAction').dataset.mode='install';$('updateAction').textContent='Cập nhật & khởi động lại';$('updateAction').disabled=false;}
  if(st.status==='error'){$('updateMessage').textContent='Cập nhật không thành công.';$('updateProgressText').textContent=st.error||'Lỗi không xác định';$('updateAction').dataset.mode='check';$('updateAction').textContent='Thử lại';$('updateAction').disabled=false;}
});
